-- ════════════════════════════════════════════════════════════
-- FINANZAS PERSONALES — Esquema completo de base de datos
-- Generado a partir de los campos usados en script.js
-- Ejecutar completo en: Supabase → SQL Editor → New query → Run
-- ════════════════════════════════════════════════════════════

-- ── 1) LIMPIEZA: elimina cualquier rastro de tablas anteriores ──
drop table if exists movimientos cascade;
drop table if exists cargos_tarjeta cascade;
drop table if exists pagos_deuda cascade;
drop table if exists deudas cascade;
drop table if exists lotes_inversion cascade;
drop table if exists ventas_inversion cascade;
drop table if exists dividendos cascade;
drop table if exists inversiones cascade;
drop table if exists posiciones_divisa cascade;
drop table if exists tasas_cambio cascade;

-- ── 2) DEUDAS ──
create table deudas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nombre text not null,
  tipo text not null,
  capital numeric not null default 0,
  fecha date not null,
  tipo_tasa text,
  tasa_fija numeric default 0,
  frecuencia text,
  cuotas integer default 0,
  es_tarjeta_auto boolean default false,
  created_at timestamptz default now()
);

-- ── 3) MOVIMIENTOS ──
-- cargo_id se vincula más abajo (dependencia circular con cargos_tarjeta)
create table movimientos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  descripcion text,
  valor numeric not null default 0,
  tipo text not null,
  fecha date not null,
  categoria text,
  subcategoria text,
  metodo_pago text,
  es_credito boolean default false,
  deuda_id bigint references deudas(id) on delete set null,
  cargo_id bigint,
  created_at timestamptz default now()
);

-- ── 4) CARGOS DE TARJETA ──
create table cargos_tarjeta (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  deuda_id bigint references deudas(id) on delete cascade,
  movimiento_id bigint references movimientos(id) on delete set null,
  fecha date not null,
  descripcion text,
  valor numeric not null default 0,
  pagado boolean default false,
  created_at timestamptz default now()
);

-- Ahora sí, vincular movimientos.cargo_id con cargos_tarjeta
alter table movimientos
  add constraint movimientos_cargo_id_fkey
  foreign key (cargo_id) references cargos_tarjeta(id) on delete set null;

-- ── 5) PAGOS DE DEUDA ──
create table pagos_deuda (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  deuda_id bigint not null references deudas(id) on delete cascade,
  fecha date not null,
  cuota numeric not null default 0,
  capital_pagado numeric default 0,
  interes numeric default 0,
  tasa_aplicada numeric default 0,
  created_at timestamptz default now()
);

-- ── 6) INVERSIONES ──
create table inversiones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tipo text not null,
  nombre text not null,
  broker text,
  origen text,
  cantidad numeric,
  precio_compra numeric,
  precio_actual numeric,
  precio_actual_divisa numeric,
  capital numeric,
  tasa_ea numeric,
  fecha_inicio date,
  fecha_vencimiento date,
  valor_compra numeric,
  valor_actual numeric,
  divisa text default 'COP',
  tc_compra numeric,
  tc_actual numeric,
  costos numeric,
  cobrado boolean default false,
  valor_cobrado numeric,
  fecha_cobro date,
  metodo_costo text default 'PROM',
  cantidad_restante numeric,
  created_at timestamptz default now()
);

-- ── 7) LOTES DE INVERSIÓN (compras individuales, costeo PEPS/promedio) ──
create table lotes_inversion (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  inversion_id bigint not null references inversiones(id) on delete cascade,
  fecha date,
  cantidad numeric default 0,
  precio_unidad numeric default 0,
  divisa_activo text default 'COP',
  tc_compra_cop numeric default 0,
  costo_cop_total numeric default 0,
  comision numeric default 0,
  divisa_comision text default 'COP',
  cantidad_restante numeric default 0,
  cerrado boolean default false,
  created_at timestamptz default now()
);

-- ── 8) VENTAS DE INVERSIÓN ──
create table ventas_inversion (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  inversion_id bigint not null references inversiones(id) on delete cascade,
  fecha date,
  cantidad numeric default 0,
  precio_venta numeric default 0,
  divisa_activo text default 'COP',
  tc_venta_cop numeric default 0,
  valor_cop numeric default 0,
  divisa_destino text default 'COP',
  comision numeric default 0,
  divisa_comision text default 'COP',
  impuesto numeric default 0,
  divisa_impuesto text default 'COP',
  metodo_costo text default 'PROM',
  ganancia_activo_cop numeric default 0,
  ganancia_fx_cop numeric default 0,
  created_at timestamptz default now()
);

-- ── 9) DIVIDENDOS / INTERESES ──
create table dividendos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  inversion_id bigint not null references inversiones(id) on delete cascade,
  fecha date,
  monto numeric default 0,
  divisa text default 'COP',
  tipo text default 'dividendo',
  destino text default 'divisa',
  tc_cop numeric default 0,
  monto_cop numeric default 0,
  impuesto_retenido numeric default 0,
  divisa_impuesto text default 'COP',
  created_at timestamptz default now()
);

-- ── 10) POSICIONES EN DIVISA (saldo vivo por moneda/cripto) ──
create table posiciones_divisa (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  divisa text not null,
  cantidad numeric default 0,
  costo_prom_cop numeric default 0,
  created_at timestamptz default now(),
  unique (user_id, divisa)
);

-- ── 11) HISTORIAL DE TASAS DE CAMBIO ──
create table tasas_cambio (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  divisa text not null,
  tasa_cop numeric not null,
  fecha date not null,
  nota text,
  created_at timestamptz default now()
);

-- ════════════════════════════════════════════════════════════
-- Índices para acelerar las consultas filtradas por usuario
-- ════════════════════════════════════════════════════════════
create index idx_movimientos_user on movimientos(user_id);
create index idx_inversiones_user on inversiones(user_id);
create index idx_deudas_user on deudas(user_id);
create index idx_pagos_deuda_user on pagos_deuda(user_id);
create index idx_cargos_tarjeta_user on cargos_tarjeta(user_id);
create index idx_lotes_inversion_user on lotes_inversion(user_id);
create index idx_ventas_inversion_user on ventas_inversion(user_id);
create index idx_dividendos_user on dividendos(user_id);
create index idx_posiciones_divisa_user on posiciones_divisa(user_id);
create index idx_tasas_cambio_user on tasas_cambio(user_id);

-- ════════════════════════════════════════════════════════════
-- Row Level Security: cada usuario solo ve y edita sus propios datos
-- ════════════════════════════════════════════════════════════
alter table movimientos       enable row level security;
alter table inversiones       enable row level security;
alter table deudas            enable row level security;
alter table pagos_deuda       enable row level security;
alter table cargos_tarjeta    enable row level security;
alter table lotes_inversion   enable row level security;
alter table ventas_inversion  enable row level security;
alter table dividendos        enable row level security;
alter table posiciones_divisa enable row level security;
alter table tasas_cambio      enable row level security;

create policy "movimientos_propio"       on movimientos       for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "inversiones_propio"       on inversiones       for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "deudas_propio"            on deudas            for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "pagos_deuda_propio"       on pagos_deuda       for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "cargos_tarjeta_propio"    on cargos_tarjeta    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "lotes_inversion_propio"   on lotes_inversion   for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ventas_inversion_propio"  on ventas_inversion  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "dividendos_propio"        on dividendos        for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "posiciones_divisa_propio" on posiciones_divisa for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "tasas_cambio_propio"      on tasas_cambio      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
